services:
  - type: web
    name: designers-jsa-dev
    runtime: node
    repo: https://github.com/faangcareers/designers-JSA
    branch: develop
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    disk:
      name: designers-jsa-dev-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: STAGE
        value: dev
      - key: NODE_ENV
        value: development
      - key: DB_PATH
        value: /var/data/app.dev.db
      - key: ENABLE_INTERNAL_CRON
        value: "true"
      - key: CRON_HOUR
        value: "9"
      - key: CRON_TZ
        value: Europe/Berlin

  - type: web
    name: designers-jsa-production
    runtime: node
    repo: https://github.com/faangcareers/designers-JSA
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    disk:
      name: designers-jsa-production-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: STAGE
        value: production
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data/app.production.db
      - key: ENABLE_INTERNAL_CRON
        value: "true"
      - key: CRON_HOUR
        value: "9"
      - key: CRON_TZ
        value: Europe/Berlin
